# Theme en skin
#remote-theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"

# Auteur
author:
  name     : "Smartbonnie"
  bio      : "Informatief, woke, verzet."
  location : "Den Haag"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
  # _personen
  - scope:
      path: ""
      type: personen
    values:
      layout: single
      author_profile: false
      share: true


locale: "nl-Nl"
title: "Bonnies Smarties"
description: "Een site vol met woke feitelijke infornatie."
masthead_title: "SmartBonnie"
breadcrumbs: true
date_format: "%Y-%m-%d"
search: true
url: "https://smartbonnie.github.io"
repository: "smartbonnie/smartbonnie.github.io"

# Header Scrips
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js


collections:
  personen:
    output: true
    permalink: /:collection/:path/

