plugins:
  - jekyll-include-cache
remote-theme: "mmistakes/minimal-mistakes"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
minimal_mistakes_skin: "dark"
locale: "nl-Nl"
title: "Bonnies Smarties"
description: "Een site vol met woke feitelijke infornatie."
masthead_title: "SmartBonnie"
breadcrumbs: true
date_format: "%Y-%m-%d"
search: true
author:
  name     : "Smartbonnie"
  bio      : "Informatief, woke, verzet."
  location : "Den Haag"

