# Theme en skin
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "dark"

# Auteur
author:
  name      : "SmartBonnie"
  bio       : "Journalisme is op sterven na dood. Bonnie pakt de handschoen op."
  avatar    : "/img/bonnie.png"
  location  : "Den Haag"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:author@smartbonnie.eu"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://smartbonnie.eu"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-url-metadata

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: "Index."
  # _personen
  - scope:
      path: ""
      type: personen
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
  # _organisaties
  - scope:
      path: ""
      type: organisaties
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
  # _muizenissen
  - scope:
      path: ""
      type: muizenissen
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
  # _vraagstukken
  - scope:
      path: ""
      type: vraagstukken
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
  # _vademecum
  - scope:
      path: ""
      type: vademecum
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
  # _feitenchecker
  - scope:
      path: ""
      type: feitenchecker
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
  # _ftm
  - scope:
      path: ""
      type: ftm
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
  # _tweets
  - scope:
      path: ""
      type: tweets 
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true
  # _verkiezingen2025
  - scope:
      path: ""
      type: verkiezingen2025
    values:
      toc: true
      toc_label: "Index."
      show_date: true
      read_time: true
      layout: single
      author_profile: true
      share: true


locale: "nl-Nl"
title: "Bonnies Smarties"
description: "Een site vol met woke feitelijke infornatie."
masthead_title: "SmartBonnie"
breadcrumbs: true
date_format: "%Y-%m-%d"
search: true
url: "https://smartbonnie.github.io"
repository: "smartbonnie/smartbonnie.github.io"

# Header Scrips
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js


collections:
  personen:
    output: true
    permalink: /:collection/:path/
  organisaties:
    output: true
    permalink: /:collection/:path/
  muizenissen:
    output: true
    permalink: /:collection/:path/
  vraagstukken:
    output: true
    permalink: /:collection/:path/
  vademecum:
    output: true
    permalink: /:collection/:path/
  feitenchecker:
    output: true
    permalink: /:collection/:path/
  ftm:
    output: true
    permalink: /:collection/:path/
  tweets:
    output: true
    permalink: /:collection/:path/
  verkiezingen2025:
    output: true
    permalink: /:collection/:path/

fediverse:
  creator: \@smartbonnie\@mastodon.nl
