plugins:
  - jekyll-include-cache
theme: "mmistakes/minimal-mistakes"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
