#!/bin/sh

cd ~/git/smartbonnie.github.io

rm -f *.md

cp -f /storage/emulated/0/Documents/Mijn\ Data/Onderzoeken/*.md .
cp -fr /storage/emulated/0/Documents/Mijn\ Data/Onderzoeken/img .
cp -fr /storage/emulated/0/Documents/Mijn\ Data/Onderzoeken/assets .

git add .
git commit -a
git push
