source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
gem "minimal-mistakes-jekyll", :git => "https://github.com/mmistakes/minimal-mistakes.git", :tag => "4.27.1"
gem "jekyll-github-metadata"
gem "jekyll-seo-tag"
gem "jekyll-include-cache"
gem "jekyll-coffeescript"
gem "jekyll-commonmark-ghpages"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-paginate"
gem "jekyll-relative-links"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-default-layout"
gem "jekyll-titles-from-headings"
